### ISSUE TITLE
Nested runs with WRF-WVT 

### ISSUE THREAD

**Issue by gtorri** [damianinsua/WRF-WVTs#2]
I'm running into some issues when trying to run WRF-WVT in nested configuration mode. I tried initializing tracers in both domains, but the values in the outer domain make perfect sense, those in the inner domain are extremely low. 

Could you please clarify how the parameters in the namelist.input should be modified when nested domains are being used (e.g., should we only use tracers in the outer or the inner domain?)? And how should the masks be modified (e.g., does every domain get a mask?)?

Thanks!

**Comment by damianinsua** [comment]
Dear Giuseppe,

If the source you want to track is within your nested domain you will need to create an additional mask, i.e. a trmask_d02 file containing the source in the nested domain. And obviously you will have to add a column in the namelist.input file, e.g. write:

tracer2dsource = 1, 1,

If you are going to work with 2D sources. Let me know if it works or you still have problems with the simulation.

Regards,


Damián Insua Costa
Non-Linear Physics Group. Fac. Physics, Lab 029. Ext 13957.
Universidade de Santiago de Compostela (Galicia, Spain).

________________________________
De: Giuseppe Torri ***@***.***>
Enviado: sábado, 4 de junio de 2022 3:29
Para: damianinsua/WRF-WVTs ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [damianinsua/WRF-WVTs] Nested runs with WRF-WVT (Issue #2)


I'm running into some issues when trying to run WRF-WVT in nested configuration mode. I tried initializing tracers in both domains, but the values in the outer domain make perfect sense, those in the inner domain are extremely low.

Could you please clarify how the parameters in the namelist.input should be modified when nested domains are being used (e.g., should we only use tracers in the outer or the inner domain?)? And how should the masks be modified (e.g., does every domain get a mask?)?

Thanks!

**Comment by gtorri** [comment]
Thanks, it all works now!
